#! /bin/sh

# Merge XDefaults
xrdb -merge ~/.Xdefaults

# Set the xcursor name
xsetroot -cursor_name left_ptr

# Start compton with the appropriate config
compton --config ~/.config/conmpton.conf -b

# Start mpd
mpd &

# Start polybar
polybar top &

# Set the wallpaper
feh --bg-fill "/home/seth/Pictures/wallpaper.png"

# Start conky
conky &

# Start sxhkd
sxhkd &

# Define bspwm screens
bspc monitor -d web term chat code music

# Define bspwm window settings
bspc config border_width		0
bspc config normal_border_color		"#282A2B"
bspc config focused_border_color	"#C52A2B"
bspc config window_gap			15

# Define various bspwm settings
bspc config split_ratio 		0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config history_aware_focus		true
bspc config click_to_focus		true

# Define bspwm pointer settings
bspc config pointer_mod 		mod1
bspc config pointer_action1		move

# Define bspwm padding
bspc config top_padding			30
bspc config bottom_padding		0
bspc config left_padding		0
bspc config right_padding		0

